### ISSUE TITLE
deployment issue

### ISSUE THREAD

**Issue by carlosiv** [LaravelDaily/Laraquiz-QuickAdminPanel#12]
i tried to deploy this in a shared hosting site and this error

> 
Parse error: syntax error, unexpected '.', expecting '&' or variable (T_VARIABLE) in /home/reviewe4/MyQuiz/vendor/symfony/var-dumper/Resources/functions/dump.php on line 18

> 

Any idea on this?

**Comment by PovilasKorop** [comment]
@carlosiv I'm guessing your PHP version is lower than 7?

**Comment by carlosiv** [comment]
Thank you. this solved my problem. I needed to change the PHP version.

**Comment by khelsisura** [comment]
my php version is 7.1.3 but still getting this error
