### ISSUE TITLE
Demo and Repository is not the same thing

### ISSUE THREAD

**Issue by wadabeewadabeedoo** [LaravelDaily/Laraquiz-QuickAdminPanel#17]
this https://laraquiz.com/

and

this https://github.com/LaravelDaily/Laraquiz-QuickAdminPanel.git

it's totally different. Is it just me who downloaded the wrong files, or you guys put this on purpose? 

Because the demo is something I look much greater than this repo.

**Comment by PovilasKorop** [comment]
@obink it is different indeed, we added more custom code to online laraquiz after publishing this free repository.

**Comment by wadabeewadabeedoo** [comment]
oh. that's how it is. Ty
