### ISSUE TITLE
Bug DOM XSS (Cross-site Scripting) in show.blade.php

### ISSUE THREAD

**Issue by lavie3k** [LaravelDaily/Laraquiz-QuickAdminPanel#18]
Hello,

I have found a security hole in the result display function. 
Line 40: {!! $result->question->code_snippet }}

Please use: **{{ $result->question->code_snippet }}**

**Comment by PovilasKorop** [comment]
@lavie3k this assumes that the question details will come from the administrator and that administrator won't hack his own system :)
