### ISSUE TITLE
Email correction

### ISSUE THREAD

**Issue by Revaaasai** [LaravelDaily/Laraquiz-QuickAdminPanel#19]
Hi 
I have downloaded  and  installed it in my domain. It is working .I have configured my email settings in .env file .For forgot password I am getting email from info@quickadminpanel.com.I am not getting email from which I have given in .env file .Where to change   info@quickadminpanel.com email ?

**Comment by PovilasKorop** [comment]
@Revaaasai https://github.com/LaravelDaily/Laraquiz-QuickAdminPanel/search?q=info%40quickadminpanel.com

**Comment by Revaaasai** [comment]
working .thanks.
