### ISSUE TITLE
variable names typo

### ISSUE THREAD

**Issue by caloyiv** [LaravelDaily/Laraquiz-QuickAdminPanel#5]
/app/Http/Controllers/QuestionsOptionsController.php

lines 69 & 71
`$questionsoption = QuestionsOption::findOrFail($id);
return view('questions_options.edit', compact('questionsoption') + $relations);`

I changed it to `questions_option` to remove undefined variable when editing an option. The same issue and solution to lines 104 & 104

**Comment by PovilasKorop** [comment]
@caloyiv thank you, fixed now.
