### ISSUE TITLE
Getting error when trying to run in windows

### ISSUE THREAD

**Issue by aminbaig** [LaravelDaily/Laraquiz-QuickAdminPanel#6]
Hi,

Do I need to have a vagarant box in order to run this?
I am getting this error when trying to run:

ConnectionException in AbstractConnection.php line 155:
No connection could be made because the target machine actively refused it. [tcp://127.0.0.1:6379]

**Comment by PovilasKorop** [comment]
@aminbaig something is wrong with your web-server/database settings (you're using XAMPP or something like that on Windows?), this error is outside of our project.

**Comment by aminbaig** [comment]
Thanks for replying,

Yes I am using Windows and xampp. I do realize that it is outside the scope
but I would really appreciate it if you can just advise me on the dev
environment I should have. Not the details, just the general indication.

Regards.

**Comment by PovilasKorop** [comment]
@aminbaig there's nothing special from any other Laravel project - database credentials should be in .env file and they should work.

**Comment by aminbaig** [comment]
Thanks again.

I will revisit the settings. Maonly it seems.like the problem is with redis
and it is not connecting to it.

I don't have redis installed so I will rectify that.

Regards.

**Comment by powolnymarcel** [comment]
I got the exact same Error.

Solution is to change : 
```
CACHE_DRIVER=redis
SESSION_DRIVER=redis
```

TO

```
CACHE_DRIVER=array
SESSION_DRIVER=file
```

**Comment by SasiSpenzer** [comment]
Thank you @powolnymarcel  ... You just saved my day
