### ISSUE TITLE
What should be URL?

### ISSUE THREAD

**Issue by bhargavtristate** [LaravelDaily/Laraquiz-QuickAdminPanel#7]
Hi

I have finished installation with all the steps but without docker.
I can see quickadmin folder created in public and also can see blade files and also run migrations.
I can't what URL should I write to run as per screen shot you have shown?

Do I need to define something in routes?

**Comment by PovilasKorop** [comment]
You should attach your domain to the /public folder of your repository, depending on web-server you use, like Homestead or something like XAMPP, please read the documentation of your web-server.

**Comment by bhargavtristate** [comment]
Perhaps! This is not related to web-server.
http://localhost/Laraquiz-QuickAdmin/public/quickadmin/
I can't see anything with above URL
I have all blade files within resources/views directory.

Can you please tell me what should be URL for this?
e.g. http://localhost/Laraquiz-QuickAdmin/public/quickadmin/login
or http://localhost/Laraquiz-QuickAdmin/public/quickadmin/

I hope you got my point. Let me know your thoughts.

**Comment by PovilasKorop** [comment]
@bhargavtristate why are you adding /quickadmin to your URL?  
I think you're missing some knowledge in how Laravel default folder structure works with web-server, please read the official documentation.

**Comment by bhargavtristate** [comment]
I have not added /quickadmin myself. I have just followed the steps.
By the way /quickadmin is in public directory.

**Comment by PovilasKorop** [comment]
Where in our instructions did you see /quickadmin as a URL? I've checked the instruction steps, it's not there. 

You should point your domain on web-server to /public and then launch http://localhost/Laraquiz-QuickAdmin/

Or http://localhost/Laraquiz-QuickAdmin/public - depending on your web-server settings.

**Comment by bhargavtristate** [comment]
I think I should ask in some another way.
Please ignore above things.
Now, I have followed all the steps.
According to you, what should be the URL to access the full working quiz as soon as I finish all the steps mentioned.

**Comment by PovilasKorop** [comment]
Again - depends on your web-server and its settings. You didn't answer what web-server you're using and how your localhost domain is configured.
Probably, it should be http://localhost/Laraquiz-QuickAdmin/

**Comment by bhargavtristate** [comment]
Yes, it's http://localhost/Laraquiz-QuickAdmin/
I have configured in Ubuntu 16.04 and it's just on my local machine.
Path is like this: /opt/lampp/htdocs/Laraquiz-QuickAdmin

**Comment by bhargavtristate** [comment]
Yes, it's http://localhost/Laraquiz-QuickAdmin/
I have configured in Ubuntu 16.04 and it's just on my local machine.
Path is like this: /opt/lampp/htdocs/Laraquiz-QuickAdmin
